version: '3.8'
name: node-mongo-project


services: 
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - db-app-network
    
    depends_on:
      - db
    

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - mongo_data:/data/db 
    networks:
      - db-app-network

networks:
  db-app-network:

volumes:
  mongo_data:
