version: '3.8'
name: node-mongo-project (+nginx & redis)


services: 
  app:
    build: .
    networks:
      - db-app-network
    
    depends_on:
      - db
      - cache
  
  nginx:
    image: nginx
    ports: 
      - "80:80"
    networks:
      - db-app-network
    configs: 
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - app

  cache:
    image: redis
    

    networks:
      - db-app-network

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - mongo_data:/data/db 
    networks:
      - db-app-network

networks:
  db-app-network:

volumes:
  mongo_data:

configs:
  nginx_config:
    file: ./nginx/nginx.conf 
